# Generated by Django 5.0.6 on 2024-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='crop_spaces',
        ),
        migrations.DeleteModel(
            name='plate_register',
        ),
    ]
